### ISSUE TITLE
Chef-client fails with NoMethodError error in fmw_inst and fmw_opatch in windows

### ISSUE THREAD

**Issue by fcassarino** [oracle/fmw-chef-cookbook#15]
I am installing SOA suite on a WIN2012R2 server using the Oracle chef FMW cookbooks.  I am getting an error and failure when trying to apply the `fmw_inst::soa_suite` and `fmw_opatch::weblogic` recipes.  Those recipes reference resources from the resources folder on each cookbook.  The error below is from the `fmw_opatch::weblogic`

`Failed Chef Client run a673eba0-3c01-4bf6-a404-bdd42b1b705f in 309.103323 seconds.
 Exception type: NoMethodError
 Exception message: undefined method 'orainst_dir' for Custom resource `mw_opatch_opatch_windows from cookbook fmw_opatch`

I am not experienced enough to know exactly how the resource should be used or how the code works, but looking at the code the state_attrs do not match the attributes above it:
```
# Copyright 2015 Oracle Corporation
# All Rights Reserved
#
# Cookbook Name:: fmw_opatch
# Resource:: opatch
#
provides :fmw_opatch_opatch, os: 'windows'

# apply or rollback the patch
actions :apply, :rollback

# Make create the default action
default_action :apply

# Opatch patch id
attribute :patch_id, kind_of: String, required: true, name_attribute: true
# Oracle home folder
attribute :oracle_home_dir, kind_of: String, required: true
# Java home folder
attribute :java_home_dir, kind_of: String, required: true
# tmp folder
attribute :tmp_dir, kind_of: String, required: true

state_attrs :patch_id, :oracle_home_dir, :java_home_dir, :orainst_dir, :os_user, :os_group, :tmp_dir

attr_accessor :exists
```
I am getting the error on :orainst_dir but I am assuming it would fail for :os_user and :os_group.  That whole line looks like it was copied from the Linux resource and does not work for the windows resource.  I had the similar error on the `fmw_inst::soa_suite` recipe was well.

Any way someone could look into this for me and let me know how I could move passed the errors?

**Comment by biemond** [comment]
Hi 

I can see it is a windows bug, too much copy paste.
https://github.com/oracle/fmw-chef-cookbook/blob/master/fmw_opatch/resources/opatch_windows.rb#L24

just remove those entries from state_attrs, that should fix it 

you can also send me a pull request.

Thanks for reporting this.

Cheers Edwin
