### ISSUE TITLE
FMW Infra

### ISSUE THREAD

**Issue by rekdt** [oracle/fmw-chef-cookbook#2]
Hello,

I was able to successfully run the chef-solo client and have a weblogic instance running with the generic weblogic installer (fmw_12.2.1.0.0_wls.jar). 

My question is, would the cookbooks be able to run with the Fusion Middleware Infrastructure (fmw_12.2.1.0.0_infrastructure.jar) as well?

**Comment by biemond** [comment]
Nice, 

indeed see this readme for some fmw examples

or change your current install_type to infra instead of the default wls

```
  "fmw_wls": {
    "source_file":         "/software/fmw_12.2.1.0.0_infrastructure.jar",
    "install_type":        "infra"  <------
  }
```

**Comment by rekdt** [comment]
Thank you very much Edwin! It worked wonderfully!
