### ISSUE TITLE
fmw_jdk --> uninitialized constant Chef::Resource::FmwJdkJdkLinuxRpm

### ISSUE THREAD

**Issue by droakes** [oracle/fmw-chef-cookbook#20]
Hey guys,

I've tried this with both custom and pre-built vagrant boxes (CentOS, RHEL 6) and with each I get this error with the fmw_jdk cookbook.  I have logged into the box and confirmed that the jdk package does indeed exist in the directory it's looking for.  Don't see anyone else having the issue so I'd hate to call it a bug but I can't seem to get around it.

kitchen.yml and system info below

**Error:**
---
       NameError
       ---------
       uninitialized constant Chef::Resource::FmwJdkJdkLinuxRpm
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/fmw_jdk/resources/jdk_linux_rpm.rb:22:in `block in class_from_file'
         /tmp/kitchen/cache/cookbooks/fmw_jdk/recipes/install.rb:71:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/fmw_jdk/recipes/install.rb:68:in `from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/fmw_jdk/resources/jdk_linux_rpm.rb:
       
        15:  default_action :install
        16:  
        17:  # Java home folder, this is the folder where the jdk will be installed
        18:  attribute :java_home_dir, kind_of: String, required: true, name_attribute: true
        19:  # Linux JDK source file, it should be a file with .rpm as extension.
        20:  attribute :source_file,   kind_of: String, required: true, callbacks:
        21:            {
        22>>             'source should have a valid JDK extension' => ->(extensions) { Chef::Resource::FmwJdkJdkLinuxRpm.validate_source_file(extensions) }
        23:            }
        24:  
        25:  state_attrs :java_home_dir
        26:  
        27:  attr_accessor :exists
        28:  
        29:  VALID_JDK_EXTENSIONS =
        30:    ['.rpm']
        31:

.kitchen.yml
---
    driver:
      name: vagrant
      provider: virtualbox

    provisioner:
      name: chef_solo

    platforms:
      - name: centos-6.7
        driver_config:
          customize:
            memory: 2048
            cpus: 1
          synced_folders:
             - ["/data01/software", "/software"]

    suites:
      - name: rpm
        run_list:
          - recipe[fmw_jdk::install]
          - recipe[fmw_jdk::rng_service]
        attributes:
          fmw:
            java_home_dir:    "/usr/java/jdk1.7.0_79"
          fmw_jdk:
            source_file:      "/software/jdk-7u79-linux-x64.rpm"
        excludes:
          - debian-7.2.0
          - windows-2012r2
          - windows-8.1
          - solaris-11.2
          - solaris-10

**System Info:**
---
    Kitchen=1.15.0
    Vagrant=1.9.3
    VirtualBox=5.1.20r114628
    chef_version=13.0.118
    platform=centos
    platform_version=6.7
    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
    program_name=chef-solo

**Comment by biemond** [comment]
Hi,

thanks for reporting.

I guess it is because of chef 13 ( this is an auto install  with kitchen),  Probably I need to change this to  version 12 or 11.

This is developed & tested for chef 11  & 12. So there are probably some breaking changes. I don't know if I can make it work for all chef versions. Maybe I need to release a separate 13 version. 

thanks Edwin

**Comment by droakes** [comment]
That was it.  Added the below line to my .kitchen.yml (to restrict it to the latest 12.x), and it ran successfully this time.  Thanks for the quick response Edwin (and for your work on this).  Much appreciated.

    provisioner:
      name: chef_solo
      require_chef_omnibus: 12

**Comment by biemond** [comment]
good to know this. There is still some work to do.

**Comment by biemond** [comment]
So I started the work on chef 13 ( started on fmw_jdk ) ,that works but I had to remove the support for chef 11.

**Comment by droakes** [comment]
Works great!  Just tested it on 13.  Thanks Edwin.
