### ISSUE TITLE
Multiple Domains?

### ISSUE THREAD

**Issue by droakes** [oracle/fmw-chef-cookbook#21]
Hey Edwin/all,

I have a need to create multiple domains.  Can this be done here (as is)?  I can easily change the data bag and run it for each domain but I'd rather do it all in one run.

Tried doing in like this in kitchen.yml (to their corresponding data bags) but it didn't like the format (as I expected).

    fmw_domain:
        databag_key: ['domain1','domain2','domain3']

Other option would be to have multiple domains in the data bag.  Can this be done?

**Comment by biemond** [comment]
Hi,

I guess if you want to do this in 1 run you have to change all the domain recipes so it accepts an array of domain objects or use a different recipe which invokes the domain recipes

thanks

**Comment by droakes** [comment]
Thanks Edwin.
