### ISSUE TITLE
{"error":["Field 'metadata.name' invalid"]}

### ISSUE THREAD

**Issue by prithivip** [oracle/fmw-chef-cookbook#24]
Not able to upload fmw-chef-cookbook to my chef server.
Getting below error upon uploading cookbook.

DK environment:
$rpm -qa | grep chef
chefdk-2.4.17-1.el6.x86_64

Chef server environment:
$rpm -qa | grep chef
chef-server-core-12.17.33-1.el6.x86_64
chef-manage-2.5.4-1.el6.x86_64
chefdk-2.4.17-1.el6.x86_64

Below command executed in chef DK
sudo knife upload cookbooks/fmw-chef-cookbook --force -VV

==============================================================
DEBUG: ---- HTTP Request Body ----
DEBUG: {"metadata":{"name":null,"description":"","long_description":"","maintainer":"","maintainer_email":"","license":"All rights reserved","platforms":{},"dependencies":{},"providing":{},"attributes":{},"recipes":{},"version":"0.0.0","source_url":"","issues_url":"","privacy":false,"chef_versions":[],"ohai_versions":[],"gems":[]},"version":"0.0.0","name":"fmw-chef-cookbook-0.0.0","cookbook_name":"fmw-chef-cookbook","root_files":[{"name":"CONTRIBUTING.md","path":"CONTRIBUTING.md","checksum":"bd7ae021b36f5d72df588e423cacf0a2","specificity":"default"},{"name":"CHANGELOG.md","path":"CHANGELOG.md","checksum":"243ce32a1ee02bade207812d35703db4","specificity":"default"},{"name":"README.md","path":"README.md","checksum":"a805829e2076393686cbe52a3c0664f2","specificity":"default"},{"name":"LICENSE","path":"LICENSE","checksum":"4db0789d88030442b61fe482ddbe61ac","specificity":"default"}],"resources":[],"providers":[],"recipes":[],"definitions":[],"libraries":[],"attributes":[],"files":[],"templates":[],"frozen?":false,"chef_type":"cookbook_version","json_class":"Chef::CookbookVersion"}
DEBUG: ---- End HTTP Request Body ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::APIVersions#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Expected JSON response, but got content-type ''
DEBUG: Response body contains:
{"error":["Field 'metadata.name' invalid"]}
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
ERROR: cookbooks failed to write: HTTP error writing: 400 "Bad Request" cause: {"error":["Field 'metadata.name' invalid"]}

**Comment by biemond** [comment]
Hi,

please try to import the subfolders you need like fmw_jdk etc and not its parent. it is not 1 big cookbook

thanks

**Comment by prithivip** [comment]
Thanks Edwin for your quick reply.

Getting below error. Let me know what I'm missing with this. Just started
first time with weblogic cookbook and im ended up with this problem.

$sudo knife cookbook upload fmw_jdk
ERROR: Could not find cookbook fmw_jdk in your cookbook path, skipping it
Uploaded 0 cookbook.

$pwd
/inet/apps/CHEF-REPO/chef-repo/cookbooks/fmw-chef-cookbook

$ll
-rw-r--r--  1 root inetadm  574 Mar  4 15:59 CHANGELOG.md
-rw-r--r--  1 root inetadm  687 Mar  4 15:59 CONTRIBUTING.md
drwxr-sr-x  9 root inetadm 4096 Mar  4 15:59 fmw_bsu
drwxr-sr-x 11 root inetadm 4096 Mar  4 15:59 fmw_domain
drwxr-sr-x 11 root inetadm 4096 Mar  4 15:59 fmw_inst
drwxr-sr-x  9 root inetadm 4096 Mar  4 15:59 fmw_jdk
drwxr-sr-x  9 root inetadm 4096 Mar  4 15:59 fmw_opatch
drwxr-sr-x 10 root inetadm 4096 Mar  4 15:59 fmw_rcu
drwxr-sr-x 11 root inetadm 4096 Mar  4 15:59 fmw_wls
-rw-r--r--  1 root inetadm 1073 Mar  4 15:59 LICENSE
-rw-r--r--  1 root inetadm 4737 Mar  4 15:59 README.md

**Comment by prithivip** [comment]
Hi Edwin,
I got it now. I missed two steps before upload.

$sudo chef generate cookbook cookbooks/fmw_wls
$sudo cp -rf fmw-chef-cookbook/fmw_wls/* fmw_wls/
$sudo knife cookbook upload fmw_wls

It works like charm.

Thanks for your heads up.

On Sun, Mar 4, 2018 at 7:28 PM, Prithiviraj Pandurangan <prithivip@gmail.com
