### ISSUE TITLE
Empty ['fmw']['java_home_dir'] causes JDK installation to be skipped. 

### ISSUE THREAD

**Issue by amyles** [oracle/fmw-chef-cookbook#3]
If I have precreated an empty directory I plan to use for java_home_dir then the fmw_jdk::install recipe skips the installation/extraction of the JDK archive.

**Comment by biemond** [comment]
Hi,

like #4  java_home_dir is global parameter of all cookbooks and should point to the full path of the used jdk. It is not used for the install location but I used it to see if it is already installed.

What is the use case to make this directory yourself, I create the parent folder and extract it to this parent directory

I can add the bin directory to this check but I need to understand, what you try to achieve.

Thanks

**Comment by amyles** [comment]
Wouldn't a check that the directory was there but empty be more user friendly? E.g. only_if do (::Dir.entries(node['fmw']['java_home_dir']) - %w{ . ..}).empty? end

**Comment by biemond** [comment]
Indeed, but why do you want to create directory yourself. if there a special reason for this.

**Comment by amyles** [comment]
Suppose it's an NFS mount where I mount the share at the JAVA_HOME location?

**Comment by biemond** [comment]
ok, interesting. that makes sense in that case, mostly I see a NFS share for all binaries or for some Wls HA domain and not just one for the JDK

I have to check EDG, mostly I see java being installed on the VM.
