### ISSUE TITLE
JDK archive extraction location not as per java_home_dir attribute

### ISSUE THREAD

**Issue by amyles** [oracle/fmw-chef-cookbook#4]
Hi 
I'm finding that the directory to which the JDK is extracted is not always the one I specify in java_home_dir. 
For instance if I set java_home_dir to /jdk/jdk8 and /jdk/jdk8 does not exist then /jdk/jdk8 is created but the JDK is extracted to /jdk/jdk1.8.0_92. The source_file is set to /jdk/jdk-8u92-linux-x64.tar.gz. 

In order for it to install I must set java_home_dir to /jdk/jdk1.8.0_92 where the final dir must match the structure of the JDK tar file.

**Comment by biemond** [comment]
Hi,

you are right java_home_dir is global parameter of all cookbooks and should point to the full path of the used jdk. It is not used for the install location but I used it to see if it is already installed.

indeed in case of tar.gz and rpm it already contains this directory name, I only create the parent dir and extract/install it to that location.

Thanks Edwin

**Comment by amyles** [comment]
Hi 
So how does one specify the JDK install directory if not via java_home_dir?

It would be useful to be able to specify a custom directory path e.g. /u01/jdk and not one that is determined by the packaging of the JDK archive. 

BR 

Angus

**Comment by biemond** [comment]
Hi Angus

What mostly is done, always use the full path provided by the package, set alternatives and after this use or set a symbolic link to this full install. 

This way you can easily patch your current environment by installing a jdk and only updating the symbolic like /u01/jdk or /usr/java/latest.

Thanks Edwin

**Comment by amyles** [comment]
AFAIK JCS installs JDK straight into a physical directory at /u01/jdk. It would be nice to be able to follow their convention. :-)
