### ISSUE TITLE
JCE is not handled

### ISSUE THREAD

**Issue by montge** [oracle/fmw-chef-cookbook#5]
The current version does not handle installation of JCE.  As a workaround we have been using the following cookbook, but it creates confusion in how the cookbooks interact with each other at times.

https://supermarket.chef.io/cookbooks/java

Recommend that JCE installation be added to functionality.

**Comment by biemond** [comment]
Are you hitting a JCE error because before Java 7 I had to do this with keys above 1024 but now I almost never have to install JCE. 

Thanks

**Comment by montge** [comment]
It may be a carry over on our side from older 10.3.6 w/ Java 6 installations.  I'll have to go back and see if I can find out where the tie in is.  Doc ID 1067411.1 seems to mention the need for JCE to utilize the stronger crypto with AES256.  Not sure if there's a better link that describes when that's needed.
