### ISSUE TITLE
Leverage Chef-vault

### ISSUE THREAD

**Issue by montge** [oracle/fmw-chef-cookbook#6]
Currently the cookbook is utilizing unencrypted databags for storage of privileged credentials (specifically the weblogic_password).  Recommend rewriting this section to utilize encrypted credentials.

**Comment by biemond** [comment]
These are just examples for chef solo. The cookbooks will detect if they encrypted or not 
See https://github.com/oracle/chef-samples/blob/master/fmw_domain/recipes/domain.rb#L19

**Comment by montge** [comment]
Got it!  I'll play around with it to see how it fits into the model I'm using.
