### ISSUE TITLE
BSU oracle_home_dir

### ISSUE THREAD

**Issue by montge** [oracle/fmw-chef-cookbook#8]
[2016-08-31T07:18:51-04:00] ERROR: undefined method `oracle_home_dir' for Custom resource fmw_bsu_bsu from cookbook fmw_bsu
[2016-08-31T07:18:51-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

In the documentation I don't see a reference to oracle_home_dir is the error above expected?

The main thing I'm seeing is that BSU tries to run everytime chef-client runs.

Recipe: fmw_bsu::weblogic
- directory[/opt/oracle/middleware/utils/bsu/cache_dir] action create (up to date)
- execute[extract DEM4] action run (up to date)
- execute[patch bsu.sh] action run
  - execute sed -e's/MEM_ARGS="-Xms256m -Xmx512m"/MEM_ARGS="-Xms1024m -Xmx1024m -XX:-UseGCOverheadLimit"/g' /opt/oracle/middleware/utils/bsu/bsu.sh > /opt/oracle/middleware/utils/bsu/bsu.sh.tmp && mv /opt/oracle/middleware/utils/bsu/bsu.sh.tmp /opt/oracle/middleware/utils/bsu/bsu.sh
- file[/opt/oracle/middleware/utils/bsu/bsu.sh] action create
  - change mode from '0644' to '0755'
  - restore selinux security context
- fmw_bsu_bsu[DEM4] action install (up to date)

**Comment by biemond** [comment]
Hi,

interesting, I will re-run test kitchen of fmw_bsu. But with wls 10.3 or 11g there is no oracle home so this is strange error.

will let you know

Thanks

**Comment by biemond** [comment]
I found it

can you remove this oracle home attribute
https://github.com/oracle/chef-samples/blob/master/fmw_bsu/resources/bsu.rb#L22
https://github.com/oracle/chef-samples/blob/master/fmw_bsu/resources/bsu_windows.rb#L20

**Comment by biemond** [comment]
Hi 

Can you tell me more about your chef environment because I get this if I run it the 2nd time. I don't see your output.

my config 

```
{
  "run_list": ["recipe[fmw_jdk::install]",
               "recipe[fmw_jdk::rng_service]",
               "recipe[fmw_wls::setup]",
               "recipe[fmw_wls::install]",
               "recipe[fmw_bsu::weblogic]"
              ],
  "fmw": {
    "java_home_dir":       "/usr/java/jdk1.7.0_75",
    "middleware_home_dir": "/opt/oracle/middleware_11g",
    "weblogic_home_dir":   "/opt/oracle/middleware_11g/wlserver_10.3",
    "version":             "10.3.6"
  },
  "fmw_jdk": {
    "source_file":         "/software/jdk-7u75-linux-x64.tar.gz"
  },
  "fmw_wls": {
    "source_file":         "/software/wls1036_generic.jar"
  },
  "fmw_bsu": {
    "patch_id":            "YUIS",
    "source_file":         "/software/p20181997_1036_Generic.zip"
  }
}
```

output

```
Recipe: fmw_bsu::weblogic
  * directory[/opt/oracle/middleware_11g/utils/bsu/cache_dir] action create[2016-08-31T16:11:08+02:00] INFO: Processing directo
ry[/opt/oracle/middleware_11g/utils/bsu/cache_dir] action create (fmw_bsu::weblogic line 19)
 (up to date)
  * execute[extract YUIS] action run[2016-08-31T16:11:08+02:00] INFO: Processing execute[extract YUIS] action run (fmw_bsu::web
logic line 27)
 (up to date)
  * execute[patch bsu.sh] action run[2016-08-31T16:11:08+02:00] INFO: Processing execute[patch bsu.sh] action run (fmw_bsu::web
logic line 37)
[2016-08-31T16:11:08+02:00] INFO: Processing execute[Guard resource] action run (dynamically defined)
MEM_ARGS="-Xms512m -Xmx752m -XX:-UseGCOverheadLimit"
[2016-08-31T16:11:08+02:00] INFO: execute[Guard resource] ran successfully
 (skipped due to not_if)
  * file[/opt/oracle/middleware_11g/utils/bsu/bsu.sh] action create[2016-08-31T16:11:08+02:00] INFO: Processing file[/opt/oracl
e/middleware_11g/utils/bsu/bsu.sh] action create (fmw_bsu::weblogic line 44)
 (up to date)
  * fmw_bsu_bsu[YUIS] action install[2016-08-31T16:11:08+02:00] INFO: Processing fmw_bsu_bsu[YUIS] action install (fmw_bsu::web
logic line 82)
[2016-08-31T16:11:08+02:00] INFO: bsu provider, bsu load current resource
[2016-08-31T16:11:16+02:00] INFO: fmw_bsu_bsu[YUIS] fired the install action
[2016-08-31T16:11:16+02:00] INFO: fmw_bsu_bsu[YUIS] already patched
 (up to date)
```
