### ISSUE TITLE
Handing Multiple Patches

### ISSUE THREAD

**Issue by montge** [oracle/fmw-chef-cookbook#9]
I've got a situation where we want to handle multiple patches, the latest security patches, and then one that handles JPA 2.0 configuration.  Have you tested handling multiple patches.  Looking through the code it doesn't look like it'd work out of the box.  I think we'd have to have a loop in the weblogic.rb to cycle through multiple values for extracting the zip files.  It looks like the command to run bsu.sh might work, since it's just a list of patches.  Correct?

**Comment by biemond** [comment]
Hi,

We provide you the bsu/opatch resource/providers to do so. As example we deliver example patch recipes for wls etc. In this case you are right now you can do only one like a bundle patch for wls.

So you can make your own cookbook and use the weblogic recipe as example. Maybe you can make an extra recipe or your recipe can handle an hash as input.

Thanks

**Comment by montge** [comment]
We figured out a way to do it in code.  We can share back if interested.

**Comment by markxnelson** [comment]
Thanks that would be great
